### ISSUE TITLE
Have to press the restart button in AxeOS to start hashing

### ISSUE THREAD

**Issue by thermosats** [skot/ESP-Miner#100]
When I plug in the power cable to start the bitaxe, the power consumption stays low and the hashing doesn't start. I have to press the restart button in AxeOS every time.

https://github.com/skot/ESP-Miner/assets/152765961/b3f4b3f3-2bd2-43cc-9c45-5a4a99edb32c

**Comment by monster4866** [comment]
try to flash a new firmware,

first download
https://github.com/skot/ESP-Miner/releases

then u can flash it here:
https://espressif.github.io/esptool-js/

**Comment by laststrawman** [comment]
I flashed my bitaxe using the above flash tool and now it is not working. I have always had success from the command line bitaxetool etc ... I guess I have to go back to that.
