### ISSUE TITLE
Automatically reconnect to wifi

### ISSUE THREAD

**Issue by pacamoto** [skot/ESP-Miner#102]
Sometimes people have issues with the wifi and if the device is disconnected, a manual restart is needed to reconnect. It should retry over and over again to reconnect to WIFI if the connection has failed.

**Comment by jddebug** [comment]
I have this issue too. If I reboot my wifi the bitAxe never seems to reconnect. Instead they seem to be stuck in the initial setup mode where they are creating a hotspot to get initial settings. I have waited over 30 minutes and they never try the wifi in settings again necessitating a reboot/power cycle to get them back online. Maybe have them try to reconnect to wifi in settings every 5 minutes to see if it is back up and if not go back to hotspot mode for 5 minutes and then try again?

**Comment by skot** [comment]
That's a good point. I think we should address this too.

We do have to be careful if we retry every 5min though, it will need to exit host AP mode to do that and that could mess up setup.

**Comment by jddebug** [comment]
Can you detect that someone has actually connected to the AP and not try the WiFi reconnect until a reboot if someone has connected?

**Comment by adrianh87** [comment]
A possible approach could be if it detects no Wifi connection, reboot, every 5 minutes.

**Comment by dreson4** [comment]
Can we have a way to simply just set max retries to max? If my router has any issue and restarts for example the miner will retry 5 times, fail and simply stop. I read the code directly there's a Wifi max retry value.

**Comment by skot** [comment]
You can put whatever number you want here, but be aware you'll have to wait that long before you can configure the WiFi initially

**Comment by skot** [comment]
Odell audibly submitted this issue, RHR May 23rd

**Comment by jddebug** [comment]
This is my most desired feature. Anytime my wifi glitches or reboots I lose miners.

**Comment by skot** [comment]
the issue is that normally we put up the setup AP when we can't find WiFi to give people a chance to configure new WiFi creds.

**Comment by jddebug** [comment]
I get that and it is necessary. Why not have it periodically try for the configured wifi though? Maybe every 5 minutes or even 10 minutes. I'd even be happy with 30 minutes. Anything would be better than never and your away for a day or two and not mining due to a wifi glitch/router reboot.

**Comment by skot** [comment]
that seems like a good idea. We have to make sure only to try the reconnect if no connections have been made to the config AP

**Comment by skot** [comment]
I think @benjamin-wilson said he's going to fix this one 😉

**Comment by skot** [comment]
I think @benjamin-wilson said he's going to fix this one for @modl21

**Comment by benjamin-wilson** [comment]
Fixed b53b641c6850756654836ff429374b745bd5393c
