### ISSUE TITLE
Error when trying to flash the miner

### ISSUE THREAD

**Issue by pinokio240** [skot/ESP-Miner#110]
Error when trying to flash the miner
![error](https://github.com/skot/ESP-Miner/assets/37944152/042880d8-77a4-41ac-b927-53ff13dd7797)
![ver_win](https://github.com/skot/ESP-Miner/assets/37944152/29bcbc9f-33f7-4836-bdd5-376b1d1e621f)
If you flash the file esp-miner-factory-v2.0.4.bin without config.cvs using Espressif. The miner starts but cannot be configured. How to flash NVS partition using Espressif? 
Should I remove 3.12?
Miner: JDHX bit lottery bm1397 v.3.8   z
P.S.
Figured it out:
1) Removed Python 3.12
2) Cleaned the registry
3) Installed Python 3.4
4) Installed esptool using the commands pip install esptool and pip install esptool --upgrade
For firmware I used ESP-prog

**Comment by skot** [comment]
you can flash just the config.cvs using bitaxetool. `bitaxetool --config ./config.cvs`

glad you got it figured out!

**Comment by johnny9** [comment]
I removed distutils from bitaxetool. bitaxetool version 0.6 should work with 3.12 on Windows now.

**Comment by pinokio240** [comment]
Now the problem is like in https://github.com/skot/ESP-Miner/issues/100. Doesn't measure power correctly and restarts. I tried different firmwares - it didn’t help.

**Comment by pinokio240** [comment]
> you can flash just the config.cvs using bitaxetool. `bitaxetool --config ./config.cvs`
> 
> glad you got it figured out!

OK
