### ISSUE TITLE
Readme no longer has build instructions

### ISSUE THREAD

**Issue by johnny9** [skot/ESP-Miner#112]
Instructions for how to build seemed to have been removed last November with the update to the bitaxetool instructions. They were likely out of date anyway. We should have these readded and updated.

**Comment by Collins-Webdev** [comment]
I took care of it. I made a pull-request. You can already check it and do the merge.

**Comment by Sjors** [comment]
Did they disappear again? I don't see build instructions in `readme.md` atm. I can probably figure it out from the CI build script?
