### ISSUE TITLE
Please bring the current session best difficulty back

### ISSUE THREAD

**Issue by weixiongmei** [skot/ESP-Miner#120]
Please bring the current session best difficulty back, rather than just showing the record high best difficulty, some of the pool doesn't show the best difficulty, and there is no where to know what's the best difficulty for the current session. Very inconvenient. Thank you!

**Comment by m6olz** [comment]
I wait for this too.

**Comment by ghost** [comment]
Valid request realtime best share should be available in the AxeOS front end could be added in the same section as the overall best share. Possible debug mode switch in settings showing as much output as possible would be something nice to have as a option.

**Comment by benjamin-wilson** [comment]
Completed in 2.1.5
