### ISSUE TITLE
Enhancements: Realtime Logs auto scrolling, Restart Button Position and Responsive Webpages for www

### ISSUE THREAD

**Issue by TheMissingNTLDR** [skot/ESP-Miner#121]
1. Consider a new web page (tab) for Realtime Logs.
2. Give users ability to Stop Auto Scrolling for Realtime Logs as and when it is needed for reading, copying, analysing convenience.
3. Not sure if Restart button can live in Settings Tab only? which could give more space on top of webpage and also save users from inadvertently clicking it. Remove it from global location.
4. Responsive Webpages for www will enhance Mobile Browsing experience.

EDIT:
Point 1 and 4 are completed in v2.1.0 (Released on 04 Mar 2024)
Point 3 is really not required now due to new design in v2.1.0
**Point 2 may still need considering**

**Comment by TheMissingNTLDR** [comment]
Upgrade Test:
I have upgraded my BM1366 to v2.1.0 and it looks and works great!

**Comment by benjamin-wilson** [comment]
Completed 2.1.1
