### ISSUE TITLE
Bug: Global Restart Button is not visible on Mobile Phone Browsing

### ISSUE THREAD

**Issue by TheMissingNTLDR** [skot/ESP-Miner#122]
Steps:
1. Using BitAxe with BM1366 here
2. Bug applies to this version only [v2.1.0](https://github.com/skot/ESP-Miner/releases/tag/v2.1.0)
3. download and upgrade to [esp-miner.bin](https://github.com/skot/ESP-Miner/releases/download/v2.1.0/esp-miner.bin) [www.bin](https://github.com/skot/ESP-Miner/releases/download/v2.1.0/www.bin)
4. Open the www website on a mobile phone via the IP address
5. Check www in both Portrait and Landscape mode
6. I am using iPhoneX and Safari App as browser
7. Actual Result: User is not able to see the (Global) Restart Button
8. Expected Result: User should be able to see the (Global) Restart Button

WORKAROUND: Add your IP to Swarm. Go to Swarm and use the little square Restart button shown there within your worker row.

**Comment by igalita** [comment]
+1

**Comment by skot** [comment]
I'm seeing the same here. restart button is nowhere to be found on iOS Safari. 
<img width="700" alt="image" src="https://github.com/skot/ESP-Miner/assets/140785/bf7b5f70-e5dc-4610-8f4c-dc63222ed6d9">

**Comment by Sledge0001** [comment]
Same on Android!

**Comment by benjamin-wilson** [comment]
Fixed eb55394d0afe550f5646d5f58a2b118b8a399aeb
