### ISSUE TITLE
Bitaxe 201 no log with 2.1.0 - which factory firmware for flashing?

### ISSUE THREAD

**Issue by TheRockaXXX** [skot/ESP-Miner#123]
After the update via https://github.com/WantClue/bitaxe-web-flasher (I need to flash it, because the update over the web interface failed with artifacts on the lcd and a not working bitaxe), I can't get any log information in the web interface. It stays empty.

Also I looked for the right firmware for the 201 board: I only can find the 204 or 205 versions a a file without number. Which one is the right one for 201 with BM1366?

Thank you!

**Comment by 19201003080114** [comment]
usually esp-miner.bin works for all models.
The factory files contain default configuration for each ASIC type

**Comment by TheRockaXXX** [comment]
Thank you. I upgraded with esp-miner.bin and it worked.
