### ISSUE TITLE
Panne Bitaxe BM1397 V3.8

### ISSUE THREAD

**Issue by Peichan83** [skot/ESP-Miner#124]
Bonjour,

Suite à une panne de wifi de mon opérateur et pendant une mise à jour du esp-miner.bin, mon bitaxe ne s'allume plus.

Il est détecter par mon réseau wifi, mais dès que je le sélectionne, cela me mets en échec de connexion.

Le Ventilateur tourne mais l'écran lcd ne s'allume plus.

Après un passage à la loupe aucun composant ne semble cramé.

Comment puis-je faire un hard reset ou comment puis-je le reconfigurer svp.

Merci par avance.

**Comment by benjamin-wilson** [comment]
Bonjour, veuillez contacter le fabricant pour les problèmes concernant les Bitaxes individuels.
