### ISSUE TITLE
Bitaxe failed to recieved New-Work after WAN-IP-Change (no WAN-IP for e.g. 120s) - Watchdog? - Bug?

### ISSUE THREAD

**Issue by seepv** [skot/ESP-Miner#138]
If the router get's a new IP from a Internet-Provider the Bitaxe failed to reconect for new work.

The same ocured after an OpenWRT-Router-Restart.

Is this a AxeOS or a Firmware Bug?

Is there e.g. a watchdog somewere (in AxeOS or Firmware) that resets the Bitaxe if recieving or submitting found Blocks failed for a certain time?

Bitaxe 204; AxeOS v2.1.1

**Comment by seepv** [comment]
@skot - If for e.g. the WAN-IP changes the mining subscribtion expires.
Without a new mining subscribtion, the Bitaxe keeps 'hashing' in a loop with old data.
That's what's going on - or am I wrong?

**Comment by skot** [comment]
The firmware can generate a lot of work by rolling extranonce. But we should notice the server is no longer connected pretty soon when attempting to submit a share.
