### ISSUE TITLE
Web UI aways show 100% fan

### ISSUE THREAD

**Issue by m6olz** [skot/ESP-Miner#141]
Web UI aways show that fan is running at 100%

![a](https://github.com/skot/ESP-Miner/assets/122750052/d64f9975-9888-4ab4-87e5-06de99dbd5b8)

**Comment by dadofsambonzuki** [comment]
I think this is a wider issue.

I'm seeing it as "Auto fan always shows the last saved value of the manual setting".

e.g. If you set it manually to 50%, restart, set it to auto, restart, it will show 50%.
