### ISSUE TITLE
Restart button

### ISSUE THREAD

**Issue by pacamoto** [skot/ESP-Miner#143]
The restart button is not showing on mobile or on the first connection to the bitaxe's network.

**Comment by 19201003080114** [comment]
Turn device to landscape, it will be at the bottom of hamburger menu

**Comment by pacamoto** [comment]
On my mac it's the same when I connect to the bitaxe wifi.

**Comment by 19201003080114** [comment]
> On my mac it's the same when I connect to the bitaxe wifi.

If you are using v2.1.0 or lower, Restart button missing is a known issue.
V2.1.1 and above fixed it.

**Comment by pacamoto** [comment]
Got it. Thanks!
