### ISSUE TITLE
SELF TEST POWER: FAIL with v2.1.2 and v2.1.3 and BItAxe Supra PCB Rev 401

### ISSUE THREAD

**Issue by hanleyp** [skot/ESP-Miner#145]
SELF TEST POWER: FAIL with v2.1.2 and v2.1.3 and BItAxe Supra PCB Rev 401

**To Reproduce**
1. Upgrade to v2.1.2 or v2.1.3 using asp-miner.bin via web or esp-miner-factory-401-v2.1.2/3 using web.
2. Reboot and see failure.
This always occurs for me with v2.1.2 and v2.1.3. v2.1.1 is working (no SELF TEST). But I had to restore with esp-miner-factory-205-v2.1.1.bin.

**Expected behavior**
SELF TEST POWER: PASS

**Hardware (please complete the following information):**
 - Bitaxe HW version: Supra 401
 - Bitaxe HW vendor: altairtech.io
 - ESP-Miner FW version: 2.1.3 and 2.1.3
 - Voltage:1.2V

**Comment by hanleyp** [comment]
Looks like 'power_consumption_pass' is set to < 13, but I'm getting higher. So far, I haven't been able to get it to PASS by setting config.cvs to 400 & 1100. Maybe it tests before applying those settings.

**Comment by Shen** [comment]
Why is this issue closed? It's still not working.

**Comment by skot** [comment]
> Why is this issue closed? It's still not working.

What's not working for you, specifically?

**Comment by Shen** [comment]
> What's not working for you, specifically?

SELF TEST POWER: FAIL
Bitaxe HW version: Supra 400
Bitaxe HW vendor: d-central.tech
ESP-Miner FW version: 2.1.3 (with https://wantclue.github.io/bitaxe-web-flasher/)
Voltage:1.2V

With V 2.1.1 the system boots regulary.

**Comment by skot** [comment]
Are you using the "factory" image? This is only for first-time programming (ie at a factory). Please try the "just update" image if you are not already.

**Comment by Shen** [comment]
> Are you using the "factory" image? This is only for first-time programming (ie at a factory). Please try the "just update" image if you are not already.

I tried. SELF TEST POWER: FAIL

**Comment by skot** [comment]
Ah, ok I think we have a confusing setup here. I'll release a new esp-miner with this cleared up, hopefully. https://github.com/skot/ESP-Miner/issues/177

in the mean time can you use v2.1.1?

**Comment by Shen** [comment]
Yes, thank you!
I will try out the new version when it is ready.
