### ISSUE TITLE
Query: BM1368 default voltage

### ISSUE THREAD

**Issue by HypeLaser** [skot/ESP-Miner#153]
Please confirm the "core voltage" setting for the BM1368 (401, Supra)? The default when the device arrived on an older firmware was running at 1200.

The [edit.components.ts](https://github.com/skot/ESP-Miner/commit/a5daff7b015fbe5331d759ef612bda937e4ab0ad#diff-c4afaa94f901daba70c27e229d732d61530ee2455fd03792375d81ed67d24387) file states the default is "1166", which is what firmware 2.1.3 now shows.

but the [edit.components.html](https://github.com/skot/ESP-Miner/commit/3df855d9b42943a455abd97224caa65ee8387da2#diff-b916291b974e18f57dcad9ca40f8f3419d8444aa4de96b85e9348a7ba4d9b0f6) states "1200".

So should it be 1200 or 1166?

As a side question, what's the consequences of having the wrong voltage set? Should I expect it to run hotter, faster, slower, rejected shares?

**Comment by 19201003080114** [comment]
<img width="402" alt="image" src="https://github.com/skot/ESP-Miner/assets/158797249/b3dd9743-4b21-4e09-9269-879767c7ad22">

Higher volt = higher temp but not necessary faster

**Comment by 19201003080114** [comment]
If it works with 1166, leave it be. Unless you want to overclock
