### ISSUE TITLE
Configs not written to NVS during compilation using ESP-IDF 5.1

### ISSUE THREAD

**Issue by developeralgo8888** [skot/ESP-Miner#16]
Note about esp-miner master repo with ESP-IDF Version 5.1:

Run the following on a fresh bitaxe v2.2 to test esp-miner Repo V5.1 

```
(1)  idf.py set-target esp32s3
(2)  idf.py menuconfig  and also 
(3)  updated the config.cvs with same configs as menuconfig (except for Freq & Vcore)
(3)  idf.py -p PORT erase-flash
(4)  idf.py -p PORT flash monitor
```

Noticed that: Stratum configurations are not written to NVS . i did have to run the bitaxetool to write stratum config to NVS

Without running bitaxetool to write the configs to NVS the miner does not seem to connect imeediately or sometimes not at all. 

`(5)  bitaxetool --port PORT --firmware esp-miner.bin --config config.cvs`

[message.txt](https://github.com/skot/ESP-Miner/files/12387968/message.txt)

**Comment by johnny9** [comment]
No configs are written to the NVS unless you use the bitaxetool. If you are compiling it yourself, you use menuconfig to configure the compiletime definitions that will be used to connect to your stratum server.
