### ISSUE TITLE
Add `password` field on Settings page (for `mining.authorize`)

### ISSUE THREAD

**Issue by plebhash** [skot/ESP-Miner#176]
The AxeOS UI only allows the user to type in a `username`, but not a `password`.

DEMAND Pool allows [Solo SV1 mining](https://www.dmnd.work/#solo-sv1), but that requires the `password` field for authentication (`mining.authorize`). It is where the bitcoin address is informed.

![image](https://github.com/skot/ESP-Miner/assets/147345153/36f88782-87bc-438f-aab5-e8b5626ed436)

Therefore, it would be desirable to add a `password` field to the AxeOS Settings UI.

cc @Fi3 @AlejandroDeLaTorre

**Comment by Fi3** [comment]
I confirm that in order to mine in solo mode with sv1 with demand you need to be able to insert a password.

**Comment by benjamin-wilson** [comment]
Maybe I'm missing something but there is already an input for a stratum password in settings.
![image](https://github.com/skot/ESP-Miner/assets/1399163/2b9118c3-ba3f-40b2-a903-7d75e3917c58)

**Comment by plebhash** [comment]
my BitAxe firmware is probably out of date, sorry for the noise

**Comment by plebhash** [comment]
@benjamin-wilson how do I download or generate a `www.bin` so I can update my UI?

**Comment by benjamin-wilson** [comment]
There's also the www.bin on the releases page. If there's no UI changes I don't upload one.
