### ISSUE TITLE
Swarm devices showing up multiple times

### ISSUE THREAD

**Issue by RuneStone0** [skot/ESP-Miner#187]
**Describe the bug**
Its possible to add the same device/IP multiple times to the swarm. Sometimes, I've experienced even adding a single IP would end up in adding two entries. So, something is off no the page where you manage your swarm.

**To Reproduce**
1. Go to Swarm
2. Add e.g. 192.168.86.40
3. Add the same IP again (e.g. 192.168.86.40)
4. See two entries on the list

**Expected behavior**
Check that only one unique (hostname/IP) can be added to the swarm.

**Screenshots & Photos**
![swarm-dup](https://github.com/skot/ESP-Miner/assets/6630442/3636d81a-f86c-4e1e-900b-1c83cfe91b75)

**Comment by WantClue** [comment]
Fixed with recent swarm update.
