### ISSUE TITLE
Change the polarity of the fan speed control signal on the EMC2101

### ISSUE THREAD

**Issue by skot** [skot/ESP-Miner#21]
This is related to a HW change on the Ultra; https://github.com/skot/bitaxe/issues/58

Due to the way the EMC2101 works when we set the default fan speed to 100%, it also "inverts" the PWM signal that controls the fan speed (on 4pin fans).

Ideally there would be a way in ESP-Miner to detect that the board is an Ultra and configure the EMC2101 to run with inverted polarity. This will be the standard going forward, so this change is essentially to support the older BM1397 bitaxen.

**Comment by johnny9** [comment]
Is this resolved with https://github.com/skot/ESP-Miner/commit/d4affd7ebb3971f8c7e186734f6cc09b4de1ce42?

**Comment by benjamin-wilson** [comment]
Yes I think so
