### ISSUE TITLE
BM1366 init() possible problem

### ISSUE THREAD

**Issue by Georges760** [skot/ESP-Miner#258]
This [line](https://github.com/skot/ESP-Miner/blob/master/components/bm1397/bm1366.c#L465C61-L465C71) in the BM1366 init() change the UART baudrate of the Chip to a higher one. So all command after this line should be ignored by the ASIC because of baudrate mismatch...

I don't understand how it is functional with this line !

**Comment by WantClue** [comment]
have you tried to match it and see what happens ? :D
