### ISSUE TITLE
mining does not resume after public-pool outage

### ISSUE THREAD

**Issue by skot** [skot/ESP-Miner#269]
after public-pool went down for the fiber upgrade, none of my devices reconnected without a manual reset

**Comment by skot** [comment]
this was a sneaky outage.. it seemed like public-pool.io was still up, so maybe the socket didn't;t close, but no new work was being sent?

People reported their hashrate slowly dropping to zero and then never recovering.

**Comment by skot** [comment]
I think the feature here would be to detect if no new `mining.notify` stratum messages have arrived within a certain timeout period.

**Comment by WantClue** [comment]
An esp restart with a certain timer or an rst to the asic could solve this.

**Comment by WantClue** [comment]
fixed with the fallback implementation
