### ISSUE TITLE
Shares accepted stop counting just short of 32767.

### ISSUE THREAD

**Issue by Entropypp** [skot/ESP-Miner#270]
Shares accepted stop counting just short of 32767. 

I suspect that this is because in global_state.h the declaration of:
uint64_t shares_accepted;
uint64_t shares_rejected

Should be declared as long.

This seems to cause issues in http_server.c when calling
cJSON_AddNumberToObject(root,"sharesAccepted", GLOBAL_STATE->SYSTEM_MODULE.shares_accepted)

**Comment by skot** [comment]
What firmware version are you running?

**Comment by Entropypp** [comment]
Verified that this happens in v2.1.8

**Comment by skot** [comment]
This fix will be in 2.1.10
