### ISSUE TITLE
DUPLICATE WORKERS ISSUE IN SWARM IN v2.1.9-5-g349b5cb-dirty 

### ISSUE THREAD

**Issue by WHALE4mMARS** [skot/ESP-Miner#282]
Note: Issues are not for customer support, configuration or discussion. For those topics please consult with your HW vendor or the OSMU Discord at: https://osmu.bitaxe.org

DUPLICATE WORKERS APPEAR IN SWARM TAB AFTER ADDING INITIAL 5-6 WORKERS. 
**To Reproduce**

Steps to reproduce the behaviour:
 
AFTER ADDING 5-6 WORKERS IN SWARM DUPLICATE WORKERS APPEAR. 

YOU CAN KEEP ADDING THE WORKERS IN SWARM IF DUPLICATES DON'T APPEAR FOR YOU EVEN AFTER 5-6 WORKERS . DUPLICATES APPEARED FOR ME AFTER 5-6 WORKERS. SO, THAT'S ALL I CAN TELL YOU. 

**Expected behavior**
AFTER ADDING 5-6 WORKERS IN SWARM DUPLICATE WORKERS APPEAR. 

**Screenshots & Photos**

![Screenshot 2024-08-10 at 19 24 34](https://github.com/user-attachments/assets/bd2e36e8-53d6-4245-873a-968896707221)
![Screenshot 2024-08-10 at 19 27 12](https://github.com/user-attachments/assets/2d643e09-2e5d-402f-8215-7aef8bed01f1)

**Hardware (please complete the following information):**
 - Bitaxe HW version: [Ultra 205, Supra 401]
 - Bitaxe HW vendor: [SOLOSATOSHI, BITCOINMERCH]
 - ESP-Miner FW version: [ v2.1.9-5-g349b5cb-dirty ]
 - Hash Frequency: 500
 - Voltage:1166
  

THANK YOU.

**Comment by OsO-1973** [comment]
Got a similar one here
Bitaxe Supra 401 2.1.10
Hash 490
1166
<img width="1358" alt="Bildschirmfoto 2024-08-18 um 06 55 41" src="https://github.com/user-attachments/assets/1e9a9874-5f1b-4b2b-acd6-95af86427913">
