### ISSUE TITLE
AxeOS overview shows "WiFi Status: Retrying"

### ISSUE THREAD

**Issue by skot** [skot/ESP-Miner#289]
the AxeOS Logs tab in the overview section shows "WiFi Status: Retrying xx" even though WiFi is connected and working fine.

<img width="387" alt="image" src="https://github.com/user-attachments/assets/849eceeb-a50f-4f33-b97a-7b01701804df">

**Comment by WantClue** [comment]
Add some logging to the retrying function and let's see why this gets called. Haven't seen this in any of my tested devices.
