### ISSUE TITLE
Track number of blocks found on dashboard and api

### ISSUE THREAD

**Issue by eandersson** [skot/ESP-Miner#290]
This is mostly for fun and wishful thinking, but for my own miners I added a tracker that I stored in nvs_config to track the number of blocks found.

e.g. this is how it shows up in my dashboard
![image](https://github.com/user-attachments/assets/3b21f77b-d5d0-4194-9b9c-984fb318e4f3)

```
cJSON_AddNumberToObject(root, "blocksFound", GLOBAL_STATE->SYSTEM_MODULE.blocks_found);
```

```
if (diff > network_diff) {
    module->FOUND_BLOCK = true;
    module->blocks_found++;
    nvs_config_set_u64(NVS_CONFIG_BLOCKS_FOUND, module->blocks_found);
    ESP_LOGI(TAG, "FOUND BLOCK!!!!!!!!!!!!!!!!!!!!!! %f > %f", diff, network_diff);
}
```

**Comment by 19201003080114** [comment]
I vote this is worthy to be included in next update 👍

**Comment by WantClue** [comment]
If you suggest implementations open a pull request please.
