### ISSUE TITLE
AxeOS on bitaxeMax 102 shows regulator temperature (which doesn't exist)

### ISSUE THREAD

**Issue by skot** [skot/ESP-Miner#291]
<img width="388" alt="image" src="https://github.com/user-attachments/assets/ca667efd-3cd7-493e-b895-52b357cb4a4a">

The BitaxeMax doesn't have a regulator that provides temperature. This gauge should be hidden on 102 / 2.2 HW

<img width="345" alt="image" src="https://github.com/user-attachments/assets/01861527-1db6-4e84-907a-f55f38c697a7">

**Comment by mrv777** [comment]
Is this still a bug?
I see `*ngIf="info.vrTemp > 0"` so I would think it only shows if it has a positive value, but maybe the BM1397 returns something odd?
