### ISSUE TITLE
Switch to a proper LCD library for the OLED

### ISSUE THREAD

**Issue by skot** [skot/ESP-Miner#299]
Espressif has a ESP-IDF library for LCD that's supports the I2C SSD1306 that we use on the Bitaxe. https://docs.espressif.com/projects/esp-idf/en/v5.2.2/esp32s3/api-reference/peripherals/lcd.html

Example for the I2C SSD1306
https://github.com/espressif/esp-idf/tree/v5.2.2/examples/peripherals/lcd/i2c_oled

**Comment by mutatrum** [comment]
LVGL?

**Comment by mutatrum** [comment]
Fixed with #539
