### ISSUE TITLE
v2.1.10 doesn´t work with Lucky Miner lvl06

### ISSUE THREAD

**Issue by TheRockaXXX** [skot/ESP-Miner#307]
Hi,

v2.1.10 doesn´t work with Lucky Miner lvl06. The previous 2.1.8 works without any probs.
On 2.1.10 the mining doesn't start and stays at 0 GH/s.

**Comment by skot** [comment]
esp-miner does not support closed source luckyminer hardware.

**Comment by pixeldoc2000** [comment]
Thas sad, but understandable.

I am in the same boat with a Lucky Miner LVL06 v2.

Mining still works with 2.1.10, but OLED Display, Temperatur and Voltage Sensor does not work anymore.

**Comment by skot** [comment]
> That is sad, but somewhat understandable.
> 
> I am in the same boat with a Lucky Miner LVL06 v2. Mining still works with 2.1.10, but OLED Display, Temperatur and Voltage Sensor does not work anymore.

this would be trivial to fix if they had released their hardware changes (as is required by the license).

**Comment by pixeldoc2000** [comment]
@skot
True, but it will be complicated to locate the "Vendor" and tell them to do so...

Maybe I find some time to pull the commits apart to figure out what did break things with Lucky Miner.

Is there anything particular I should be looking for?

**Comment by skot** [comment]
IMO you should look for a legit Bitaxe

**Comment by pixeldoc2000** [comment]
Found out why OLED Display, Temperatur and Voltage Sensor did not work anymore after FW v2.1.8 .

In CVS / NVS config I had a custom devicemodel: `devicemodel,data,string,LV06`.

Everything is fine after I change it to regular Bitaxe 1366 (ultra) settings: `devicemodel,data,string,ultra`.
