### ISSUE TITLE
Support bm1397 in mode_1

### ISSUE THREAD

**Issue by BONIIXS** [skot/ESP-Miner#31]
Hey there I just wanted to ask if it was possible to use the firmware with a custom miner with the same hardware but the BM1397 will be in mode 1, is it possible?

**Comment by skot** [comment]
Yes, definitely! AFAIK esp-miner doesn't care what mode the ASIC is in.

**Comment by johnny9** [comment]
What does mode 1 refer to?

**Comment by skot** [comment]
"Mode" in this context is a pin on the ASIC that reverses the side the data input and output pins are on. It dramatically simplifies PCB routing.

**Comment by BONIIXS** [comment]
Thanks for the answer skot

**Comment by BONIIXS** [comment]
Thanks for the answer but does it also support chaining(multiple asic chips in series)

**Comment by skot** [comment]
we have added theoretical support for multiple ASICs to esp-miner. But until one of the hex designs is done it's untested.

**Comment by BONIIXS** [comment]
I think I can make one

**Comment by BONIIXS** [comment]
I've just started, and I think it'll take me about 3 to 7 days to finish. It's going to be like a hexagonal-designed battle axe. how many ASIC chips I should use?
