### ISSUE TITLE
Simplify the display information

### ISSUE THREAD

**Issue by skot** [skot/ESP-Miner#313]
I think we can remove a lot of the information from the OLED. It's all available in AxeOS and the API for people who really care.

1st screen:
- Hashrate
- Efficiency
- Best Difficulty
- Temp

2nd screen:
- pool url
- esp-miner version
- IP address

It might also help to modernize the display library at the same time, as suggested in #299

**Comment by WantClue** [comment]
Working on this this week

**Comment by WantClue** [comment]
https://github.com/WantClue/ESP-Miner-WantClue/tree/simplify_screen

**Comment by WantClue** [comment]
@skot https://github.com/WantClue/ESP-Miner-WantClue/tree/simplify_screen
