### ISSUE TITLE
Hash rate display not correct for graphing

### ISSUE THREAD

**Issue by zcht** [skot/ESP-Miner#315]
**Describe the bug**
With higher ASIC clock rates and therefore higher hash rates for a bitaxis, the scaling of the display is not output correctly. This example shows a Bitaxe Supra with the current 2.1.10 firmware. In my case, a hash speed range between 900-1430 Gh/s is delivered. See corresponding markings. 

**To Reproduce**

**Caution, only carry out steps with sufficient cooling to avoid damage.** 

1. Set 800 Mhz and 1.375 vCore
1. Switch to the dashboard and wait until the hash speed is displayed in the graph

**Screenshots & Photos**
<img width="935" alt="anzeige" src="https://github.com/user-attachments/assets/2c813660-4cb5-448e-9d73-437dfbeca17d">

**Hardware:**
 - Bitaxe HW version: Supra 400 - BM1368
 - Bitaxe HW vendor: D-Central
 - ESP-Miner FW version: 2.1.10
 - Hash Frequency: 800
 - Voltage: 1.375
 - Pool URL, Port, User: solo ckpool or publicpool

**Comment by mrv777** [comment]
I'll add if the number is under 10 to show 2 decimal places, I think that will be good then
