### ISSUE TITLE
Wifi never goes back to connected after WiFi connection failed

### ISSUE THREAD

**Issue by eandersson** [skot/ESP-Miner#320]
In the UI the status is stuck at something like this after being disconnected from the WiFi and then successfully re-establishing the connection again.
> WiFi Status: Retrying 100

![image](https://github.com/user-attachments/assets/cc0332ee-9add-488c-a7a4-914682e80fe4)

Steps to reproduce
- Connect device to WiFi.
- Restart WiFi Router / AP.
- Reconnect to device. WebUI under Logs should say `Connected!`, but instead says `Retrying: X`.

**Comment by andersonsilva87** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by Dinar813** [comment]
after upgrading to version 2.1.10, I received the same error.
![Снимок экрана 2024-09-06 в 12 06 24](https://github.com/user-attachments/assets/c8d264ae-a0e0-40a5-8caf-632829237cc3)

**Comment by eandersson** [comment]
This is a duplicate of https://github.com/skot/ESP-Miner/issues/289
