### ISSUE TITLE
make AxeOS plot lines straight.

### ISSUE THREAD

**Issue by skot** [skot/ESP-Miner#328]
<img width="462" alt="image" src="https://github.com/user-attachments/assets/564ec7e5-e1e5-4829-80a5-db08d6a20d9f">

It's kinda silly IMO to have the plot lines be these bezier-like curves. Can we make them just straight lines? It will avoid this "time travel" look.

**Comment by mrv777** [comment]
This should be changing tension: .4, to tension: 0
(Might be able to get away with a little curve like .1)
