### ISSUE TITLE
add the last four hex digits of the MAC address to the WiFi name

### ISSUE THREAD

**Issue by skot** [skot/ESP-Miner#33]
We need a unique name for the AP SSID incase there are multiple bitaxe running nearby.

I have seen this done by appending the last 2 bytes of the Wi-Fi MAC address to the default SSID.

**Comment by benjamin-wilson** [comment]
https://github.com/skot/ESP-Miner/commit/a30a7ef05fd2661172ae6e171246c8a080f5fb8e
