### ISSUE TITLE
Strange Errors from Nerdaxe Board

### ISSUE THREAD

**Issue by nG64** [skot/ESP-Miner#335]
I noticed some Strange behavior on my nerdaxe board. It reboots every now and then randomly, and after some time mining on public pool my difficulty resets, and i get errors in the log, only option is to restart the miner.

Overview
Model:	BM1366
Uptime:	5 hours
WiFi Status:	Connected!
Free Heap Memory:	103436
Version:	v2.1.9-36-gaecb8af-dirty
Board Version:	204

0CCF8000
₿ (18151143) bm1366Module: Invalid job found, 0x30
₿ (18154723) bm1366Module: Job ID: 30, Core: 77/4, Ver: 0CCF8000
₿ (18154733) bm1366Module: Invalid job found, 0x30
₿ (18158313) bm1366Module: Job ID: 30, Core: 77/4, Ver: 0CCF8000
₿ (18158313) bm1366Module: Invalid job found, 0x30
₿ (18161893) bm1366Module: Job ID: 30, Core: 77/4, Ver: 0CCF8000

Current Version: v2.1.9-36-gaecb8af-dirty

URL:	public-pool.io
Port:	21496

**Comment by 19201003080114** [comment]
This is for "regular" ESP-Miner
For Nerdaxe related issues, go to their Github
https://github.com/BitMaker-hub/ESP-Miner-NerdAxe
