### ISSUE TITLE
Overheat mode should be more obvious in AxeOS

### ISSUE THREAD

**Issue by skot** [skot/ESP-Miner#342]
Right now it is easy to miss that the Bitaxe is in overheat mode in AxeOS. I suggest we put a big red banner at the top of every AxeOS tab.

**Comment by Barnminer** [comment]
I agree. When I assist people with issues, they did not even notice this.

**Comment by skot** [comment]
I'd also like to have the overheat mode checkbox **checked** by default. Then the user can uncheck it to "Disable overheated mode", causing the whole thing to disappear

**Comment by skot** [comment]
@eandersson do you have any time to help with this? I'm hopeless with this front end stuff 😅
the [overheat_mode_improvements](https://github.com/skot/ESP-Miner/tree/overheat_mode_improvements) branch might be a good one to work off

**Comment by eandersson** [comment]
> @eandersson do you have any time to help with this? I'm hopeless with this front end stuff 😅 the [overheat_mode_improvements](https://github.com/skot/ESP-Miner/tree/overheat_mode_improvements) branch might be a good one to work off

Haha I am too, but I can take a stab at it this weekend.
