### ISSUE TITLE
Efficacy not Efficiency

### ISSUE THREAD

**Issue by AndySchroder** [skot/ESP-Miner#345]
The web UI presents `efficiency` in terms of `J/TH`. `Efficiency` is a unitless quantity that measures the output over the input or the maximum possible output. You could present `efficiency` in terms of [Landauer's principle](https://en.wikipedia.org/wiki/Landauer%27s_principle) if you want to present `efficiency`. However, I'd encourage you to present the metric `J/TH` as an `Efficacy` instead, since that is what it really is.

**Comment by skot** [comment]
The correct term is "performance per watt", often referred to as power efficiency. The unitless efficiency term you are talking about is mechanical efficiency, but that's not really relevant in computing.
