### ISSUE TITLE
Lower the default hash frequency and core voltage for Gamma

### ISSUE THREAD

**Issue by skot** [skot/ESP-Miner#369]
The stock heatsink and fan on the Gamma cannot reliably handle more than 525MHz @ 1100mV.

We should change the firmware defaults.

**Comment by jrkalf** [comment]
@skot I partially agree with you on that one. With the stock yellow cooling brick & springloaded clamps you won't get it more stable than that at regular room temperatures. 
I would suggest that it can handle 595MHz @ 1150mV, but only under the condition that the springloaded clamps are replaced by M3*8 bolts and nuts. 

The springloaded clamps in combination with the thermal paste is not performing well. There's multiple articles out on the web now, I've seen this first hand on my gamma.

**Comment by benjamin-wilson** [comment]
525@1150 seems to be the minimum voltage to be stable

**Comment by skot** [comment]
okay, lets go with 525MHz/1150mV as the default. This needs to be adjusted in the cvs file as well as the AxeOS settings drop downs.
