### ISSUE TITLE
Asic model invalid

### ISSUE THREAD

**Issue by Dolu89** [skot/ESP-Miner#39]
I tried to flash my bitaxe to the latest version but I now got Invalid asic model on the screen.
Model is BM1397

It's broken since this commit https://github.com/skot/ESP-Miner/commit/706ee510ba509d9a04445e87a3d426ddaccd9f98
It works great on the previous one (bc4afd39b70b874ed5ab2743dddde888670b908b)

Tell me if you need more info, I don't know what to provide

**Comment by johnny9** [comment]
You need to write manufacturing data into flash once. Specifically the field "asicmodel". You can use bitaxetool to write this info. Documentation will be coming shortly but if you need more info check the OSMU discord.
