### ISSUE TITLE
Not Mining

### ISSUE THREAD

**Issue by laststrawman** [skot/ESP-Miner#43]
I am connected to my WiFi but I don't seem to be mining. How do I debug? I am using a Bitaxe board purchased from D-Central. I am trying to connect to public-pool.io 
Also, my led displays ASIC model invalid so I am wondering if there is something wrong with my build config.

**Comment by laststrawman** [comment]
Ok ... update. I flashed the BM1397 following this link: https://github.com/skot/ESP-Miner/releases/tag/v2.0.0
I now can see it talking to public-pool.io but I am still not mining. I definitely have the BM1397 2.2 chip so I set the config.cvs to those settings.

**Comment by geg780** [comment]
Do you have a proper power supply? At least 4a are needed.

**Comment by laststrawman** [comment]
![image](https://github.com/skot/ESP-Miner/assets/29166705/cb99da19-58d1-4616-9d84-8b7fa703308a)

**Comment by laststrawman** [comment]
I have seen my miner on public-pool.io
![image](https://github.com/skot/ESP-Miner/assets/29166705/7d03a366-850f-4aa4-b756-1e840d8c600c)

**Comment by laststrawman** [comment]
I think you are right ... I looked at my power supply and it has an output of 5v = 1A

**Comment by geg780** [comment]
Yeah thats the issue

**Comment by laststrawman** [comment]
I am fixed ... it was the power supply.
