### ISSUE TITLE
CKPool - Primary URL link not working with the latest PR

### ISSUE THREAD

**Issue by STSMiner1** [skot/ESP-Miner#451]
CKPool - Primary URL needs updating, it was missed.

https://github.com/skot/ESP-Miner/pull/423

File
"home.component.ts"

https://github.com/skot/ESP-Miner/blob/master/main/http_server/axe-os/src/app/components/home/home.component.ts#L209-L244

![CKPoolURLerror](https://github.com/user-attachments/assets/241ac244-cd0d-4763-a084-22f1635c4756)

**Comment by mrv777** [comment]
https://github.com/skot/ESP-Miner/pull/452
