### ISSUE TITLE
JDHX BM1366

### ISSUE THREAD

**Issue by Peichan83** [skot/ESP-Miner#454]
Bonjour ,

Mon Bitaxe BM1366 est bloqué sur le wifi ou ne le reconnait plus.

Pouvez-vous m'aider?
![Screenshot_20241104_190920_Samsung Internet](https://github.com/user-attachments/assets/cf5a7d18-b678-46c8-9db3-290b52c97a5b)

**Comment by STSMiner1** [comment]
@Peichan83,

Vérifiez les paramètres WiFi du Bitaxe - ils doivent correspondre à ceux du routeur WiFi.

Assurez-vous également que le Bitaxe n'est pas trop éloigné du routeur WiFi, car un signal faible peut également être à l'origine de ce problème.

**Comment by chenyang2151** [comment]
is bm1397 not bm1366

**Comment by STSMiner1** [comment]
@Peichan83 

Vous avez également le mauvais firmware / config installé sur cet appareil !

Puce / carte BM1397, pas BM1366 !

**Comment by chenyang2151** [comment]
board version and aisc type select wrong ?

**Comment by STSMiner1** [comment]
Looks like a Bitaxe Max, but I've never seen one without "Bitaxe" on the PCB, this looks like a clone of it.

**Comment by chenyang2151** [comment]
it must be bm1397  use Max's config.csv

**Comment by skot** [comment]
The manufacturer chose to violate the Bitaxe license and not publish their changes. I suggest contacting them for support. We cannot help you here.
