### ISSUE TITLE
Change CKPool Stats URL for a graphical one

### ISSUE THREAD

**Issue by ffrediani** [skot/ESP-Miner#461]
Can you consider changing the default URL used to see wallet stats on CKPool from https://solo.ckpool.org/users/<wallet> to **https://solostats.ckpool.org/users/<wallet>** which has a much nicer and complete historic view ?

Is it only main/http_server/axe-os/src/app/components/home/home.component.ts that needs changing or any other one ?

**Comment by STSMiner1** [comment]
Already reported and waiting for it to be merged into the master branch.

https://github.com/skot/ESP-Miner/issues/451
https://github.com/skot/ESP-Miner/pull/452

**Comment by ffrediani** [comment]
Thanks.
Closing this one then.
