### ISSUE TITLE
Chip-Temperature 2.3.0 -> 2.4.0 

### ISSUE THREAD

**Issue by mark0st83** [skot/ESP-Miner#512]
I took the plunge yesterday and updated my Gamma 601 to version 2.4.0. Everything seems to have worked so far.

However, the fan is now running much faster than before. The chip temperature is showing about 10 degrees Celsius warmer than before.
Because of this, the fan is running about 2000 RPM faster.

The frequency and voltage remain the same, but this isn’t visible in the 2.3.0 screenshot.

What temperature or operating condition is considered correct now?

![IMG_5218](https://github.com/user-attachments/assets/5e2ca17a-2402-457a-9434-af3652cedb54)
![IMG_5217](https://github.com/user-attachments/assets/9f068650-9f07-4dd9-8357-67cbd2c9ff53)

**Comment by STSMiner1** [comment]
2.4.0 fixes an issue with temps being under reported in 2.3.0.

https://github.com/skot/ESP-Miner/pull/483

**Comment by mark0st83** [comment]
Ok, so the 45 degrees reported in 2.3.0 was wrong? Ok thats a lot „inaccurat“ 😅

**Comment by skot** [comment]
Gamma ASIC temperature measurement before v2.4.0 was incorrect. It could be too high or too low.
