### ISSUE TITLE
Interrupt startup loop

### ISSUE THREAD

**Issue by benjamin-wilson** [skot/ESP-Miner#52]
If the wifi credentials are correct but the pool information is not or the pool is not available/compatible the system will continuously restart.

**Comment by SACREDHAZE1** [comment]
HOW TO RESET SETTINGS MANUALY ON HARDWARE MINE HAS THIS ISSUE

**Comment by benjamin-wilson** [comment]
> HOW TO RESET SETTINGS MANUALY ON HARDWARE MINE HAS THIS ISSUE

Please refrain from using caps lock... 

Anyway, turn off the wifi router or move it out of range and the bitaxe will create its own SSID again so you can connect directly.

**Comment by SACREDHAZE1** [comment]
still has same issue mines 2 accepted and wifi reset

----- Original Message -----

**Comment by benjamin-wilson** [comment]
Ok that does not fall under this issue then, please contact the place you purchased it from or OSMU discord help channel for configuration/pool help.

**Comment by benjamin-wilson** [comment]
I've run into more situation where this can happen. We need a general way to catch a boot loop.
