### ISSUE TITLE
fix hardcoded version mask on BM1366

### ISSUE THREAD

**Issue by skot** [skot/ESP-Miner#54]
Currently esp-miner always uses the BM1366 default(?) `0x1fffe000` as the version mask. Technically esp-miner should configure the BM1366 to use the version mask the stratum server & client negotiate, even if most of the time it's `0x1fffe000`

**Comment by johnny9** [comment]
Likely just need to write the mask to register A4

![version_rolling](https://github.com/skot/ESP-Miner/assets/985648/83cc9d28-9d4b-4f7e-a76f-5e8948e6efdb)
