### ISSUE TITLE
v2.4.1 swarm feature not showing the hash rate of the NerdQAxe

### ISSUE THREAD

**Issue by AhmeraDec** [skot/ESP-Miner#545]
All devices in my network are found correctly but the HashRate column for my NerdQAxe shows 'NaNundefined' although the device is running correctly and WantClue's browser extension also shows the NerdQAxe correctly.

**Comment by 19201003080114** [comment]
NerdQAxe runs off a variant of ESP-miner so not all features of the latest ESP-miner are supported.
