### ISSUE TITLE
Should reconnect if no updates from stratum after a certain amount of time

### ISSUE THREAD

**Issue by johnny9** [skot/ESP-Miner#65]
If the pool has dropped the miner's subscription but the tcp connection is still active the Bitaxe can get stuck mining for nothing. We need to have a sanity timer to restart the connection/subscription so it doesn't get stuck.

**Comment by benjamin-wilson** [comment]
ACK Yes, needed badly

**Comment by skot** [comment]
This is the goal of #272

**Comment by WantClue** [comment]
Has been fixed with #363
