### ISSUE TITLE
verbindung bricht ab, factory flash geht nicht

### ISSUE THREAD

**Issue by Lollo76** [skot/ESP-Miner#67]
Hello,

I get the normal firmware ﬂashed, but I have the problem that after a few 30 seconds, it writes underwolting that the power supply is the one from bitconmerch and has a constant 5.2xv, I wanted to flash the factory file and it doesn't work because it keeps restarting the flash breaks off after 27%. The problem is that it restarts from the beginning without any settings after 10 minutes or 3 hours.... now nothing shows in the log file in settings... does anyone have an idea?
The model with USB type C FW 2.01 was installed

**Comment by skot** [comment]
Make sure you have the barrel power connector inserted all the way.

**Comment by Lollo76** [comment]
The plug is in as far as it will go, it just jumps from the picture where it says shares accepted to the wifi
<img width="1055" alt="Unbenannt PNG4" src="https://github.com/skot/ESP-Miner/assets/98686265/58e74ab7-cd64-4451-a2e3-5c3edf7e8553">

**Comment by Lollo76** [comment]
<img width="938" alt="5" src="https://github.com/skot/ESP-Miner/assets/98686265/47ff2e3a-874b-4d19-8531-ab59ff6d7324">

**Comment by benjamin-wilson** [comment]
You need to fix the restarting issue first, can you post the realtime logs when it happens

**Comment by Lollo76** [comment]
hi it showed me this data when booting, then I updated the web.bin, the connection was interrupted due to the undervolting, now I can no longer access the website, but I can under USB ESP tool (website). to access it... the data he showed me...
dx:0,
₿
₿
₿ dx:1 (ifx:0, 48:5d:35:ab:7f:bd), tid:1, ssn:0, winSi
₿
₿
₿ dx:0 (ifx:0, 48:5d:35:ab:7f:bd), tid:0, ssn:58, winSi
₿
₿
₿ dx:0,
₿
₿
₿ dx:1,
₿
₿
₿ dx:0 (ifx:0, 48:5d:35:ab:7f:bd), tid:0, ssn:60, winSi
₿
₿
₿ dx:1 (ifx:0, 48:5d:35:ab:7f:bd), tid:1, ssn:0, winSi
₿
₿
₿ dx:1,
₿
₿
₿ dx:1 (ifx:0, 48:5d:35:ab:7f:bd), tid:1, ssn:0, winSi
₿
₿
₿ dx:1,
₿
₿
₿ dx:1 (ifx:0, 48:5d:35:ab:7f:bd), tid:1, ssn:0, winSi
₿

**Comment by Lollo76** [comment]
<img width="598" alt="esp" src="https://github.com/skot/ESP-Miner/assets/98686265/2cb27bcf-023e-4b08-9b97-2921876cf56d">

**Comment by benjamin-wilson** [comment]
Closing inactivity
