### ISSUE TITLE
Wi-Fi password is stored in plain text.

### ISSUE THREAD

**Issue by ray77** [skot/ESP-Miner#68]
Available for everyone here:
http://ip/api/system/info

**Comment by skot** [comment]
@benjamin-wilson can we omit the WiFi passwd from the API?

**Comment by benjamin-wilson** [comment]
Yes

**Comment by benjamin-wilson** [comment]
Fixed https://github.com/skot/ESP-Miner/commit/84c06110f60c7c382ea4ad742ee9018d3daf8ec3

**Comment by johnny9** [comment]
Does the web ui handle the missing value?

**Comment by benjamin-wilson** [comment]
It does but I should probably put in a fake placeholder

**Comment by ray77** [comment]
> It does but I should probably put in a fake placeholder

or any hash, generated from a unique esp device id, wifi-password and mac address.
This would still be a real, fairly secure password that can be used by the ESP to log in.
just an idea.
