### ISSUE TITLE
API and Webserver crashes 

### ISSUE THREAD

**Issue by ray77** [skot/ESP-Miner#70]
When many requests come in (eg. many Home Assistant restarts for testing), the web server (Web-App & API) crashes.
However, mining continues. Sometimes after a certain time everything is ok again without restarting.
I've set the polling frequency to the sensor to one minute and it seems to work well.

**Comment by WantClue** [comment]
This is probably due to the limited capabilities of the ESP32S3 and not a specific issue. Therefore this issue will be closed.
