### ISSUE TITLE
shutdown core voltage regulator

### ISSUE THREAD

**Issue by skot** [skot/ESP-Miner#75]
Recent BitaxeUltra versions (since 202, I believe) have the ability to turn off the TPS40305 ASIC core voltage regulator. 

it's called `PWR_EN` and it's attached to ESP32 GPIO10

We should shutdown the ASIC power when;
- temperature is too high
- the barrel jack is not inserted

**Comment by benjamin-wilson** [comment]
https://github.com/skot/ESP-Miner/commit/ef344f236dda1e7a1dd91cd7556308c456466620
