### ISSUE TITLE
detect barrel jack insertion

### ISSUE THREAD

**Issue by skot** [skot/ESP-Miner#76]
Since Bitaxe version 204 we have the ability to detect if the 5V barrel jack is inserted or not. This signal is called `PLUG_SENSE` and it's connected to the ESP32 GPIO12. `PLUG_SENSE` should go high when the barrel jack is inserted.

We should use this to disable the Core voltage regulator (see #75) when the barrel jack is disconnected (meaning we are powered by USB).

**Comment by benjamin-wilson** [comment]
https://github.com/skot/ESP-Miner/commit/ef344f236dda1e7a1dd91cd7556308c456466620
