### ISSUE TITLE
The low voltage warning threshold is too high

### ISSUE THREAD

**Issue by skot** [skot/ESP-Miner#77]
Several people are getting the low voltage warning in AxeOS, despite their bitaxe working just fine.

<img width="665" alt="image" src="https://github.com/skot/ESP-Miner/assets/140785/826ad224-1e5a-49cb-8cd7-e5cc826a90eb">

The threshold should probably be more like 4.5V

**Comment by benjamin-wilson** [comment]
Fixed in main
