### ISSUE TITLE
temp sensor faults might be trigging over temp shutdown

### ISSUE THREAD

**Issue by skot** [skot/ESP-Miner#78]
Some users have reported the Bitaxe running at normal temps and then all of the sudden going into the low hash freq "over temp shutdown" mode.

It's suspected that the EMC2101 might return erroneous temperatures or go into a fault mode every now and then causing this.

**Comment by benjamin-wilson** [comment]
We need some more info about this - i've never encountered it. erroneous readings or soldering issues? counterfeit IC?
