### ISSUE TITLE
OTA software update gone wrong, bricked miner.

### ISSUE THREAD

**Issue by Habies** [skot/ESP-Miner#88]
After a ota update my miner stopped working.
No more display and no wifi.
Is it possible to update the esp32 with a USB to serial interface?
My miner does not have a usb connector.
The board is a JDHX Bit Lottery BM1397 v3.8
Is there a tuturial how to flash the esp32 with a usb-serial converter or a esp-programmer?

**Comment by skot** [comment]
You need to reprogram the ESP32-S3 using the ESP-PROG programmer and bitaxetool and/or esptool software. There are several generic ESP32 tutorials out there on this.

unfortunately the manufacturer of your bitaxe has decided to modify the design and not publish documentation on their changes, so you’re on your own there.

**Comment by WantClue** [comment]
You can also use A Serial-to-USB Bridge. I did this in one of my first videos about it. It does require a bit of soldering of steady hands with all the pins.
With this information now I close this issue.
