### ISSUE TITLE
Feature Request: Additional Stats

### ISSUE THREAD

**Issue by StarGateMiner** [skot/ESP-Miner#91]
Hi, 

I was wondering if you can add to the AxeOS HomePage page similar stats as NerdMiner has.

(I also have this device and aware of a ongoing project to merge NerdMiner with BitAxe)

It be nice for people who like to keep the webpage open during the day on their desktops.

![stats](https://github.com/skot/ESP-Miner/assets/3984251/4094a3b0-2ee5-45f4-b585-25a2ef0ef66e)

For me it be great to have a enhanced uptime feature as can visually see movement also to help with debug.

Thoughts?

**Comment by skot** [comment]
Doesn't AxeOS have all these things? What do you mean by "enhanced uptime"?
