### ISSUE TITLE
Frecuency and Core Voltage settings lost after random reboots

### ISSUE THREAD

**Issue by github-block** [skot/ESP-Miner#92]
Time to time, there are random reboots and the settings for Frequency and Core Voltage go to blank. Then the bitaxe lower the power consumption to 2-3w and the hashing stops. 

When it happens, I'm able to set the values again and reset it and then everything start working again.

**Comment by DobQA** [comment]
Can you provide more details which firmware you running, I sometimes have random reboots but not been able the point of reboot in logs but I do not have my settings reset. Maybe worth updating to latest firmware

**Comment by github-block** [comment]
I'm using version 2.04 on board 202. I'll flash 206 and check as you suggested. Also, as I mentioned, the issue occurs randomly and it could take some days to happen again.

**Comment by benjamin-wilson** [comment]
It is going into overheating protection mode. What do you have for frequency and voltage settings? What are your temperatures?

**Comment by benjamin-wilson** [comment]
Who is the manufacturer?

**Comment by github-block** [comment]
I currently have 3 devices from 2 manufacturers and the issue happens in all of them time to time:
rgzen.com (Spain)
silexperience.company.site (France)

**Comment by StarGateMiner** [comment]
See here its similar issue: https://github.com/skot/ESP-Miner/issues/85
But I do not get on mine the loss of values.

**Comment by benjamin-wilson** [comment]
Could you take a clear, closeup picture of U7 component on the back?

**Comment by benjamin-wilson** [comment]
![image](https://github.com/skot/ESP-Miner/assets/1399163/e4c17c56-cf00-4695-8b4c-6bf0b2a93236)

It's possible these might be counterfeit IC's I'll have to contact the manufacturers

**Comment by benjamin-wilson** [comment]
Hmm manufacturers get them from DK, so nothing of particular interest there. Lets leave this issue open to gather more data.

**Comment by CaptainCodeman** [comment]
Just had the same thing happen - the auto fan control had also turned off and was set to max (the fan noise is what alerted me). It also had some message about "S19".

I restarted and it seems fine, I don't _think_ temps where high (it's normally 55-59 range) but I'll make a note if it happens again.

I'm already running v2.0.6

**Comment by github-block** [comment]
@CaptainCodeman , exactly.. I forgot to mention that the auto fan control also got turned off

**Comment by skot** [comment]
this really sounds like over temp mode. can one of you get a screenshot of the whole AxeOS dashboard page after this happens?

**Comment by benjamin-wilson** [comment]
Closing, no response, seems to be over temp.

**Comment by CaptainCodeman** [comment]
Sorry, whenever this happened I restarted it and forgot about the screenshot!

I did take the heatsink off both of mine and cleaned off and re-applied thermal paste and they have been fine since. There was an ungodly amount of paste on there which I don't think was helping - it would have been way too much even for a big Intel CPU.

Something to check if you come across this issue.
