### ISSUE TITLE
About board version distinction

### ISSUE THREAD

**Issue by kakawlala** [skot/ESP-Miner#94]
I got my device from Bitcoin Merch and it has 201 printed on the board.  After updating to version 2.0.7.bin, the power management distinction shows that the board is 204.  I'm really curious if this distinction is correct?

![P_20240121_154244_1](https://github.com/skot/ESP-Miner/assets/89348834/e71e4be1-cff8-48c9-adde-da680595e7f1)

![Screenshot_20240121-153600_Chrome_1](https://github.com/skot/ESP-Miner/assets/89348834/7315927b-4556-41cc-9e5f-c772a5121f66)

Check the 204 board on the Internet. The welding position of ESP32-S3-WROOM-1 should be aligned with the board.
Is my board really 204 instead of 201?

![52-large_default_1](https://github.com/skot/ESP-Miner/assets/89348834/33a7c00b-57fb-4e52-87ed-5c0540824560)

**Comment by StarGateMiner** [comment]
I just updated and my board version says: Board Version 0.11? is this version 201? wonder why its showing in this format.

**Comment by WantClue** [comment]
This is something that needs to be adjusted from the manufacture side.
But for the web flasher this is also an issue. I keep this one open until I do have different board version flashs available and keep you posted
