### ISSUE TITLE
When the mining pool rejects a submission, the rejected shares are not correctly incremented.

### ISSUE THREAD

**Issue by AxisRay** [skot/ESP-Miner#95]
As shown in the picture, my submission was rejected by the pool.
![image](https://github.com/skot/ESP-Miner/assets/6546326/8da004b7-c968-4ff6-ade9-0df12f7ae0b5)
However, the `result` field in the returned JSON data is `null`.
https://github.com/skot/ESP-Miner/blob/23599cf46f3668af58d252915b347fa14eedd8cf/components/stratum/stratum_api.c#L123-L141
So, in the above code, the result of `if (result_json != NULL && cJSON_IsBool(result_json)) {` is false
Because `null` is not vaild bool value.
Therefore, message->response_success is not being assigned correctly.

**Comment by skot** [comment]
Ah, good catch. this would be nice to get fixed so we can see how many shares are _actually_ rejected

**Comment by benjamin-wilson** [comment]
Fixed https://github.com/skot/ESP-Miner/commit/feda6609c10b1c37b14fa4f7366f16e4949c30a0
