### ISSUE TITLE
Bitaxetool - Python v3.12 no longer supports 'distutils' module

### ISSUE THREAD

**Issue by qubyt3** [skot/ESP-Miner#96]
Hello Team! I noticed when playing around with the new firmware release 2.0.7 yesterday, that if we try and use the bitaxetool to update it will no longer work if users have installed the latest Python v3.12. 
The 'distutils' module has been depreciated, see PEP 632 - Deprecate distutils module. 

I'm not sure if you guys already knew about this but I thought I would let you know just in case. 

Take care!

**Comment by skot** [comment]
I seem to remember there is a fix for this. @johnny9 do you remember?

**Comment by johnny9** [comment]
Fix is to use an older python. This affects windows users primarily. I should fix this asap. It's trivial to fix just need to stop forgetting.

**Comment by johnny9** [comment]
This should now be fixed with the latest version of bitaxetool. `pip install --upgrade bitaxetool`.
