### ISSUE TITLE
System reboots

### ISSUE THREAD

**Issue by Sledge0001** [skot/ESP-Miner#97]
System reboots unexpectedly between 4-10 hours using stock settings on firmware v2.0.7 

Issue does not occur on firmware 2.0 4.

**Comment by yeg0rpetrov** [comment]
I do have the same issue. But it reboots after 23 hours. Link for context https://damus.io/note1wkgnm62hy55n68h5ccypxajce4z9jvppt3ew4cpj6tcp64s8ffrqsvd5ml

**Comment by skot** [comment]
> System reboots unexpectedly between 4-10 hours using stock settings on firmware v2.0.7 
> 
> 
> 
> Issue does not occur on firmware 2.0 4.

Is this with Ocean pool also?

**Comment by Sledge0001** [comment]
CK's pool.

**Comment by Sledge0001** [comment]
Unfortunately I did not. But it seems to happen only on 2.0.7 it's very stable going back to 2.0.4

**Comment by yeg0rpetrov** [comment]
Also just switched from ocean to the https://solo.ckpool.org and it's like restarting every 15 minutes none stop. I tried to re flash the latest firmware again but same issue

**Comment by yeg0rpetrov** [comment]
> Also just switched from ocean to the https://solo.ckpool.org and it's like restarting every 15 minutes none stop. I tried to re flash the latest firmware again but same issue 

Update. 14 hours it's running none stop but I already have a first signs that restart is coming. I can't access dashboard via IP. I bought Bitaxe 204 from open source miner com. Attached photo of the board. Maybe will be helpful. ![image](https://github.com/skot/ESP-Miner/assets/62068896/0c36ee14-b3a0-4e72-8771-521cc4c7ef22)

**Comment by benjamin-wilson** [comment]
Are you leaving the dashboard open on a computer?

Can you screenshot the whole AxeOS home page please. 
If you can capture the crash in the logs that would also be helpful

**Comment by yeg0rpetrov** [comment]
No I don't leave it open. And can't access it right now: says that "Safari can't open the page because the network connection was lost" tried to turn on/off wifi on my phone and laptop same issue.

**Comment by skot** [comment]
this sounds like a networking issue maybe? Can you connect to your router and confirm the bitaxe has an IP on your network?

**Comment by benjamin-wilson** [comment]
How far away is the bitaxe from your wireless access point?

**Comment by yeg0rpetrov** [comment]
Connected devices from router page. espressif is Bitaxe 
All good on my end ![image](https://github.com/skot/ESP-Miner/assets/62068896/4b7b2d37-2e2e-4534-a8d0-614109c23e8b)

**Comment by Sledge0001** [comment]
So here's something interesting the 2 xBitAxe's I have from Opensourceminer.com are on 2.0.7 and are stable. The 1 got from altairtech has the issues with 2.0.7

**Comment by benjamin-wilson** [comment]
> So here's something interesting the 2 xBitAxe's I have from Opensourceminer.com are on 2.0.7 and are stable. The 1 got from altairtech has the issues with 2.0.7

Well I made them both ;) Can you screenshot the AxeOS dashboard on the one with issues?

**Comment by Sledge0001** [comment]
![20240131_112150](https://github.com/skot/ESP-Miner/assets/125903519/69e28557-6717-4ec2-9184-3d54cbf9f7bc)
![20240131_112218](https://github.com/skot/ESP-Miner/assets/125903519/64ae82b8-f15e-4e30-9c61-47f39593a5e5)


Here's the one that's acting odd on 2.0.7 :)

**Comment by benjamin-wilson** [comment]
How did you update to 207? Please screenshot AxeOS

**Comment by Sledge0001** [comment]
![17067295812422223052997492265710](https://github.com/skot/ESP-Miner/assets/125903519/7df05fef-c48b-459f-884d-79251a6e61fe)
![17067295415858403048997014709002](https://github.com/skot/ESP-Miner/assets/125903519/05a270d8-90c3-4af1-8255-9438afe08aaf)

Firmware was updated via the AxeOS ui

**Comment by Sledge0001** [comment]
I'll try the firmware update again and see if I experience the issue again.

**Comment by benjamin-wilson** [comment]
Ok, please screenshot the overview section again when it's updated

**Comment by Sledge0001** [comment]
![Uploading 17067302173794605531277617052254.jpg…]()

**Comment by yeg0rpetrov** [comment]
I was late. It restarted again while I was figuring out how to use minicom. But seems like I found the error in log ![image](https://github.com/skot/ESP-Miner/assets/62068896/d9493ebb-62f9-4cb9-a2cc-391a48b3b390)

**Comment by Sledge0001** [comment]
![17067308225428597156168692981611](https://github.com/skot/ESP-Miner/assets/125903519/e1c3d9af-28a2-4d0d-8b77-75f542ff69c2)
And it just crashed.

**Comment by yeg0rpetrov** [comment]
> I was late. It restarted again while I was figuring out how to use minicom. But seems like I found the error in log ![image](https://github.com/skot/ESP-Miner/assets/62068896/d9493ebb-62f9-4cb9-a2cc-391a48b3b390)

![image](https://github.com/skot/ESP-Miner/assets/62068896/1b222426-928b-4606-9ed0-ea4e0331f6b0)

**Comment by benjamin-wilson** [comment]
What is being used for power supplies?

**Comment by benjamin-wilson** [comment]
Oh @Sledge0001 change your vcore to 1200, this is the default. It looks like it changed in the update?

**Comment by Sledge0001** [comment]
> Oh @Sledge0001 change your vcore to 1200, this is the default. It looks like it changed in the update?

That's where it's set as per the ui.
![17067346664112091804107494252842](https://github.com/skot/ESP-Miner/assets/125903519/675d9b9f-5fec-4ef7-89e1-c7385e296667)

**Comment by monster4866** [comment]
u need a better power supply, i have 8 bitaxe, all came with a chep power supply, u need above +5000mv, good 5100-5300mv

https://github.com/skot/bitaxe/issues/118#issuecomment-1904615683

**Comment by yeg0rpetrov** [comment]
I heard that I can burn it if more powerful power supply

**Comment by monster4866** [comment]
> I heard that I can burn it if more powerful power supply

thats why mr volta invented volt ;)

u should plug only a 5v supply in it

**Comment by Sledge0001** [comment]
Over 24 hours online with no rebooting!

**Comment by yeg0rpetrov** [comment]
24 hours another one reboot! Ordering this one power supply in hope that gonna fix the issue! https://a.co/d/5srOIj4

I received this one with Bitaxe: https://opensourceminer.com/products/5v-5a-power-supply

**Comment by yeg0rpetrov** [comment]
> 24 hours another one reboot! Ordering this one power supply in hope that gonna fix the issue! https://a.co/d/5srOIj4
> 
> I received this one with Bitaxe: https://opensourceminer.com/products/5v-5a-power-supply

I know Benjamin check this thread as well since he was active on here. Your website where I bought the Bitaxe can't be reached! In my email I simply asked to ship back the Bitaxe I bought from you to test it and here what is your website responding to me. ![image](https://github.com/skot/ESP-Miner/assets/62068896/af74ba26-557a-427e-89b8-59e20ddad502)

**Comment by benjamin-wilson** [comment]
> > 24 hours another one reboot! Ordering this one power supply in hope that gonna fix the issue! https://a.co/d/5srOIj4
> > I received this one with Bitaxe: https://opensourceminer.com/products/5v-5a-power-supply
> 
> I know Benjamin check this thread as well since he was active on here. Your website where I bought the Bitaxe can't be reached! In my email I simply asked to ship back the Bitaxe I bought from you to test it and here what is your website responding to me. ![image](https://private-user-images.githubusercontent.com/62068896/302011957-af74ba26-557a-427e-89b8-59e20ddad502.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5MzQ0NzAsIm5iZiI6MTcwNjkzNDE3MCwicGF0aCI6Ii82MjA2ODg5Ni8zMDIwMTE5NTctYWY3NGJhMjYtNTU3YS00MjdlLTg5YjgtNTllMjBkZGFkNTAyLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwM1QwNDIyNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZjEzYTM3MDhhNjcxYTdiOGE1Njc4NWQzMDYwMzA3YmNiMDYzMTZlZGZjNDJhODk5ZDY2YzA5MmYxOGVmMTQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.F0hyxbpj-oi16p_8Ct72V3Fm7llHnoNpo6gqZprpb6A)

You can email me directly: admin@opensourceminer.com if you want to discuss any issues with your order.

**Comment by yeg0rpetrov** [comment]
Was able to cut the log file during restart. Here is log file.
[bitaxe log restarts.txt](https://github.com/skot/ESP-Miner/files/14159978/bitaxe.log.restarts.txt)

**Comment by yeg0rpetrov** [comment]
> Was able to cut the log file during restart. Here is log file.
> 
> [bitaxe log restarts.txt](https://github.com/skot/ESP-Miner/files/14159978/bitaxe.log.restarts.txt)
> 
> 

After another 17 hours it has restarted. According to the Ben I have wifi network connection issues. I doubt that this is the case. I did a restart of the modem, talked with the Comcast and everything is healthy. At some point the best difficulty stops going up and it restarts.

**Comment by benjamin-wilson** [comment]
I am also investigating a possible memory leak that might be causing this issue.

**Comment by yeg0rpetrov** [comment]
> > Was able to cut the log file during restart. Here is log file.
> > 
> > [bitaxe log restarts.txt](https://github.com/skot/ESP-Miner/files/14159978/bitaxe.log.restarts.txt)
> > 
> > 
> 
> After another 17 hours it has restarted. According to the Ben I have wifi network connection issues. I doubt that this is the case. I did a restart of the modem, talked with the Comcast and everything is healthy. At some point the best difficulty stops going up and it restarts.    

UPDATE! I have tried 2.0.7 and 2.0.6 versions of firmware and device is restarting within ~24 hours. 
After Ben's suggestion to roll back to 2.0.4 device isn't crashing and hashing over 24 hours now. 
The only conclusion what I can make now is that it's not my wifi network connection issue. Might be something with firmware and I am not only the one have this issue. ![image](https://github.com/skot/ESP-Miner/assets/62068896/3a940ea9-c693-43a4-8e88-33239cd1eb79)![image](https://github.com/skot/ESP-Miner/assets/62068896/3f26b373-0bf4-4a79-8ab1-579a840ed788)![image](https://github.com/skot/ESP-Miner/assets/62068896/ee1c0a8f-4e0c-41e2-81a6-269a951dd556)![image](https://github.com/skot/ESP-Miner/assets/62068896/27133add-ec21-416b-bf47-689bf0c6f0fc)![image](https://github.com/skot/ESP-Miner/assets/62068896/276bf290-4275-450c-93c5-d81398242263)![image](https://github.com/skot/ESP-Miner/assets/62068896/e7144581-9ff2-42e4-99c1-b610e6d46128)![image](https://github.com/skot/ESP-Miner/assets/62068896/d666a5f8-1842-4dbd-9522-dde4fed82f17)![image](https://github.com/skot/ESP-Miner/assets/62068896/b67e0886-3653-481b-b109-85d89a716149)![image](https://github.com/skot/ESP-Miner/assets/62068896/00c807d9-c943-4e04-90fb-7aabcc45480c)

**Comment by benjamin-wilson** [comment]
![PXL_20240206_180034572](https://github.com/skot/ESP-Miner/assets/1399163/3123cfa3-e3ae-4058-ba6a-c0eed01c150d)
![PXL_20240206_180059840](https://github.com/skot/ESP-Miner/assets/1399163/b33d9a45-f112-4407-813b-cbb2e7ccc51c)
![PXL_20240206_180109486](https://github.com/skot/ESP-Miner/assets/1399163/bc0f3afa-ec85-4478-8e52-5aada42585ca)

2.0.7 Going strong, no memory leaks.

**Comment by yeg0rpetrov** [comment]
> @yeg0rpetrov I can't help but notice on your home screen the board version is missing... 
> 
> 
> 
> I'm wondering if with all your troubleshooting something went missing... 
> 
> 
> 
> Possibly flashing your device with some basic manufacturing data to the NVS partition with the correct firmware and a proper config.cvs file might solve your issue. 
> 
> 
> 
> 1. Download Skot ESB-Miner repo from Git to your downloads and unzip it. ./Downloads/ESP-Miner-207
> 
> 2. Download the esp-miner-factory-204-v2.0.7.bin and place in the ESP-Miner folder ./Downloads/ESP-Miner-207/
> 
> 3. Open VS Code, Copy and Paste config.cvs.example and rename the copied file to: config.cvs
> 
> 4. Open config.cvs file and edit the following fields: 
> 
> 
> 
> key,type,encoding,value
> 
> main,namespace,,
> 
> wifissid,data,string,**myssid**
> 
> wifipass,data,string,**mypass** 
> 
> stratumurl,data,string,**solo.ckpool.org**
> 
> stratumport,data,u16,**3333**
> 
> stratumuser,data,string,**mywallet ID+workername**
> 
> stratumpass,data,string,**x**
> 
> asicfrequency,data,u16,**485**
> 
> asicvoltage,data,u16,**1200**
> 
> asicmodel,data,string,**BM1366**
> 
> devicemodel,data,string,**ultra**
> 
> boardversion,data,string,**v2.0.4**
> 
> flipscreen,data,u16,1
> 
> invertfanpol,data,u16,1
> 
> autofanspeed,data,u16,1
> 
> fanspeed,data,u16,100
> 
> --> HIT CTRL-S and SAVE
> 
> 
> 
> 5. Connect your bitaxe
> 
> 6. Select the correct port it connected to (bottom left), select the workspace folder you're working from when prompt 
> 
> 
> 
> 7. Open a terminal and type: bitaxetool --port /dev/cu.usbmodem1101 (or wtv port your Bitaxe is connected to) --config ./config.cvs --firmware ./esp-miner-factory-204-v2.0.7.bin 
> 
> note: Bitaxetool need python version 3.11.7 or earlier, it will not work with the latest python v3.12
> 
> 
> 
> Your bitaxe will flash, reboot and start hashing again. Report back your finding. Take a particular attention the Heap memory: is it steadily going down, or hovering +- a couple 1000 bytes. 
> 
> 
> 
> I think WantClue has good tutorial on hes Youtube channel on how to do this, Bitaxe V2 a new update.
> 
> 
> 
> Hope this help, let us know if you have any questions. :) 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 

The board version probably missing cause I downgraded firmware to the 2.0.4 🤔 Seems like a hell of steps 😄Thank you, will try to do re flash in that way.

**Comment by benjamin-wilson** [comment]
> > @yeg0rpetrov I can't help but notice on your home screen the board version is missing...
> > I'm wondering if with all your troubleshooting something went missing...
> > Possibly flashing your device with some basic manufacturing data to the NVS partition with the correct firmware and a proper config.cvs file might solve your issue.
> > 
> > 1. Download Skot ESB-Miner repo from Git to your downloads and unzip it. ./Downloads/ESP-Miner-207
> > 2. Download the esp-miner-factory-204-v2.0.7.bin and place in the ESP-Miner folder ./Downloads/ESP-Miner-207/
> > 3. Open VS Code, Copy and Paste config.cvs.example and rename the copied file to: config.cvs
> > 4. Open config.cvs file and edit the following fields:
> > 
> > key,type,encoding,value
> > main,namespace,,
> > wifissid,data,string,**myssid**
> > wifipass,data,string,**mypass**
> > stratumurl,data,string,**solo.ckpool.org**
> > stratumport,data,u16,**3333**
> > stratumuser,data,string,**mywallet ID+workername**
> > stratumpass,data,string,**x**
> > asicfrequency,data,u16,**485**
> > asicvoltage,data,u16,**1200**
> > asicmodel,data,string,**BM1366**
> > devicemodel,data,string,**ultra**
> > boardversion,data,string,**v2.0.4**
> > flipscreen,data,u16,1
> > invertfanpol,data,u16,1
> > autofanspeed,data,u16,1
> > fanspeed,data,u16,100
> > --> HIT CTRL-S and SAVE
> > 
> > 5. Connect your bitaxe
> > 6. Select the correct port it connected to (bottom left), select the workspace folder you're working from when prompt
> > 7. Open a terminal and type: bitaxetool --port /dev/cu.usbmodem1101 (or wtv port your Bitaxe is connected to) --config ./config.cvs --firmware ./esp-miner-factory-204-v2.0.7.bin
> > 
> > note: Bitaxetool need python version 3.11.7 or earlier, it will not work with the latest python v3.12
> > Your bitaxe will flash, reboot and start hashing again. Report back your finding. Take a particular attention the Heap memory: is it steadily going down, or hovering +- a couple 1000 bytes.
> > I think WantClue has good tutorial on hes Youtube channel on how to do this, Bitaxe V2 a new update.
> > Hope this help, let us know if you have any questions. :)
> 
> The board version probably missing cause I downgraded firmware to the 2.0.4 🤔 Seems like a hell of steps 😄Thank you, will try to do re flash in that way.

Please don't do that, it's incorrect

**Comment by yeg0rpetrov** [comment]
Damn! 1 day and 8 hours it restarted again on 2.0.4 
I give up ![image](https://github.com/skot/ESP-Miner/assets/62068896/daddbb7b-89c0-4813-b9aa-ac69729ced2c)

**Comment by benjamin-wilson** [comment]
Okay it seems conclusive now. This is a network/wireless radio issue. I'm closing the issue.
